<?php
/**
 * CdnSettings
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Управляемых сервисов
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.6.1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * CdnSettings Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CdnSettings implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Cdn_Settings';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'caching_time' => 'int',
        'follow_origin_redirect' => '\OpenAPI\Client\Model\CdnSettingsFollowOriginRedirect',
        'caching_time_browser' => '\OpenAPI\Client\Model\CdnSettingsCachingTimeBrowser',
        'ignore_cookie' => 'bool',
        'ignore_query_string' => 'bool',
        'stale' => '\OpenAPI\Client\Model\CdnSettingsStale',
        'geo_acl' => '\OpenAPI\Client\Model\CdnSettingsGeoAcl',
        'referer_acl' => '\OpenAPI\Client\Model\CdnSettingsRefererAcl',
        'ip_address_acl' => '\OpenAPI\Client\Model\CdnSettingsIpAddressAcl',
        'redirect_http_to_https' => 'bool',
        'user_agent_acl' => '\OpenAPI\Client\Model\CdnSettingsUserAgentAcl',
        'tokenized_url_secure_key' => '\OpenAPI\Client\Model\CdnSettingsTokenizedUrlSecureKey',
        'allowed_http_methods' => '\OpenAPI\Client\Model\CdnSettingsAllowedHttpMethods',
        'http3_enabled' => 'bool',
        'gzip_compression' => '\OpenAPI\Client\Model\CdnSettingsGzipCompression',
        'content_slice' => 'bool',
        'static_request_headers' => '\OpenAPI\Client\Model\CdnSettingsStaticRequestHeaders',
        'cors' => '\OpenAPI\Client\Model\CdnSettingsCors',
        'static_response_headers' => '\OpenAPI\Client\Model\CdnSettingsStaticResponseHeader',
        'response_headers_hiding_policy' => '\OpenAPI\Client\Model\CdnSettingsResponseHeadersHidingPolicy'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'caching_time' => 'uint32',
        'follow_origin_redirect' => null,
        'caching_time_browser' => null,
        'ignore_cookie' => null,
        'ignore_query_string' => null,
        'stale' => null,
        'geo_acl' => null,
        'referer_acl' => null,
        'ip_address_acl' => null,
        'redirect_http_to_https' => null,
        'user_agent_acl' => null,
        'tokenized_url_secure_key' => null,
        'allowed_http_methods' => null,
        'http3_enabled' => null,
        'gzip_compression' => null,
        'content_slice' => null,
        'static_request_headers' => null,
        'cors' => null,
        'static_response_headers' => null,
        'response_headers_hiding_policy' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'caching_time' => false,
		'follow_origin_redirect' => false,
		'caching_time_browser' => false,
		'ignore_cookie' => false,
		'ignore_query_string' => false,
		'stale' => false,
		'geo_acl' => false,
		'referer_acl' => false,
		'ip_address_acl' => false,
		'redirect_http_to_https' => false,
		'user_agent_acl' => false,
		'tokenized_url_secure_key' => false,
		'allowed_http_methods' => false,
		'http3_enabled' => false,
		'gzip_compression' => false,
		'content_slice' => false,
		'static_request_headers' => false,
		'cors' => false,
		'static_response_headers' => false,
		'response_headers_hiding_policy' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'caching_time' => 'caching_time',
        'follow_origin_redirect' => 'follow_origin_redirect',
        'caching_time_browser' => 'caching_time_browser',
        'ignore_cookie' => 'ignore_cookie',
        'ignore_query_string' => 'ignore_query_string',
        'stale' => 'stale',
        'geo_acl' => 'geo_acl',
        'referer_acl' => 'referer_acl',
        'ip_address_acl' => 'ip_address_acl',
        'redirect_http_to_https' => 'redirect_http_to_https',
        'user_agent_acl' => 'user_agent_acl',
        'tokenized_url_secure_key' => 'tokenized_url_secure_key',
        'allowed_http_methods' => 'allowed_http_methods',
        'http3_enabled' => 'http3_enabled',
        'gzip_compression' => 'gzip_compression',
        'content_slice' => 'content_slice',
        'static_request_headers' => 'static_request_headers',
        'cors' => 'cors',
        'static_response_headers' => 'static_response_headers',
        'response_headers_hiding_policy' => 'response_headers_hiding_policy'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'caching_time' => 'setCachingTime',
        'follow_origin_redirect' => 'setFollowOriginRedirect',
        'caching_time_browser' => 'setCachingTimeBrowser',
        'ignore_cookie' => 'setIgnoreCookie',
        'ignore_query_string' => 'setIgnoreQueryString',
        'stale' => 'setStale',
        'geo_acl' => 'setGeoAcl',
        'referer_acl' => 'setRefererAcl',
        'ip_address_acl' => 'setIpAddressAcl',
        'redirect_http_to_https' => 'setRedirectHttpToHttps',
        'user_agent_acl' => 'setUserAgentAcl',
        'tokenized_url_secure_key' => 'setTokenizedUrlSecureKey',
        'allowed_http_methods' => 'setAllowedHttpMethods',
        'http3_enabled' => 'setHttp3Enabled',
        'gzip_compression' => 'setGzipCompression',
        'content_slice' => 'setContentSlice',
        'static_request_headers' => 'setStaticRequestHeaders',
        'cors' => 'setCors',
        'static_response_headers' => 'setStaticResponseHeaders',
        'response_headers_hiding_policy' => 'setResponseHeadersHidingPolicy'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'caching_time' => 'getCachingTime',
        'follow_origin_redirect' => 'getFollowOriginRedirect',
        'caching_time_browser' => 'getCachingTimeBrowser',
        'ignore_cookie' => 'getIgnoreCookie',
        'ignore_query_string' => 'getIgnoreQueryString',
        'stale' => 'getStale',
        'geo_acl' => 'getGeoAcl',
        'referer_acl' => 'getRefererAcl',
        'ip_address_acl' => 'getIpAddressAcl',
        'redirect_http_to_https' => 'getRedirectHttpToHttps',
        'user_agent_acl' => 'getUserAgentAcl',
        'tokenized_url_secure_key' => 'getTokenizedUrlSecureKey',
        'allowed_http_methods' => 'getAllowedHttpMethods',
        'http3_enabled' => 'getHttp3Enabled',
        'gzip_compression' => 'getGzipCompression',
        'content_slice' => 'getContentSlice',
        'static_request_headers' => 'getStaticRequestHeaders',
        'cors' => 'getCors',
        'static_response_headers' => 'getStaticResponseHeaders',
        'response_headers_hiding_policy' => 'getResponseHeadersHidingPolicy'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('caching_time', $data ?? [], null);
        $this->setIfExists('follow_origin_redirect', $data ?? [], null);
        $this->setIfExists('caching_time_browser', $data ?? [], null);
        $this->setIfExists('ignore_cookie', $data ?? [], null);
        $this->setIfExists('ignore_query_string', $data ?? [], null);
        $this->setIfExists('stale', $data ?? [], null);
        $this->setIfExists('geo_acl', $data ?? [], null);
        $this->setIfExists('referer_acl', $data ?? [], null);
        $this->setIfExists('ip_address_acl', $data ?? [], null);
        $this->setIfExists('redirect_http_to_https', $data ?? [], null);
        $this->setIfExists('user_agent_acl', $data ?? [], null);
        $this->setIfExists('tokenized_url_secure_key', $data ?? [], null);
        $this->setIfExists('allowed_http_methods', $data ?? [], null);
        $this->setIfExists('http3_enabled', $data ?? [], null);
        $this->setIfExists('gzip_compression', $data ?? [], null);
        $this->setIfExists('content_slice', $data ?? [], null);
        $this->setIfExists('static_request_headers', $data ?? [], null);
        $this->setIfExists('cors', $data ?? [], null);
        $this->setIfExists('static_response_headers', $data ?? [], null);
        $this->setIfExists('response_headers_hiding_policy', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets caching_time
     *
     * @return int|null
     */
    public function getCachingTime()
    {
        return $this->container['caching_time'];
    }

    /**
     * Sets caching_time
     *
     * @param int|null $caching_time caching_time
     *
     * @return self
     */
    public function setCachingTime($caching_time)
    {

        if (is_null($caching_time)) {
            throw new \InvalidArgumentException('non-nullable caching_time cannot be null');
        }

        $this->container['caching_time'] = $caching_time;

        return $this;
    }

    /**
     * Gets follow_origin_redirect
     *
     * @return \OpenAPI\Client\Model\CdnSettingsFollowOriginRedirect|null
     */
    public function getFollowOriginRedirect()
    {
        return $this->container['follow_origin_redirect'];
    }

    /**
     * Sets follow_origin_redirect
     *
     * @param \OpenAPI\Client\Model\CdnSettingsFollowOriginRedirect|null $follow_origin_redirect follow_origin_redirect
     *
     * @return self
     */
    public function setFollowOriginRedirect($follow_origin_redirect)
    {

        if (is_null($follow_origin_redirect)) {
            throw new \InvalidArgumentException('non-nullable follow_origin_redirect cannot be null');
        }

        $this->container['follow_origin_redirect'] = $follow_origin_redirect;

        return $this;
    }

    /**
     * Gets caching_time_browser
     *
     * @return \OpenAPI\Client\Model\CdnSettingsCachingTimeBrowser|null
     */
    public function getCachingTimeBrowser()
    {
        return $this->container['caching_time_browser'];
    }

    /**
     * Sets caching_time_browser
     *
     * @param \OpenAPI\Client\Model\CdnSettingsCachingTimeBrowser|null $caching_time_browser caching_time_browser
     *
     * @return self
     */
    public function setCachingTimeBrowser($caching_time_browser)
    {

        if (is_null($caching_time_browser)) {
            throw new \InvalidArgumentException('non-nullable caching_time_browser cannot be null');
        }

        $this->container['caching_time_browser'] = $caching_time_browser;

        return $this;
    }

    /**
     * Gets ignore_cookie
     *
     * @return bool|null
     */
    public function getIgnoreCookie()
    {
        return $this->container['ignore_cookie'];
    }

    /**
     * Sets ignore_cookie
     *
     * @param bool|null $ignore_cookie ignore_cookie
     *
     * @return self
     */
    public function setIgnoreCookie($ignore_cookie)
    {

        if (is_null($ignore_cookie)) {
            throw new \InvalidArgumentException('non-nullable ignore_cookie cannot be null');
        }

        $this->container['ignore_cookie'] = $ignore_cookie;

        return $this;
    }

    /**
     * Gets ignore_query_string
     *
     * @return bool|null
     */
    public function getIgnoreQueryString()
    {
        return $this->container['ignore_query_string'];
    }

    /**
     * Sets ignore_query_string
     *
     * @param bool|null $ignore_query_string ignore_query_string
     *
     * @return self
     */
    public function setIgnoreQueryString($ignore_query_string)
    {

        if (is_null($ignore_query_string)) {
            throw new \InvalidArgumentException('non-nullable ignore_query_string cannot be null');
        }

        $this->container['ignore_query_string'] = $ignore_query_string;

        return $this;
    }

    /**
     * Gets stale
     *
     * @return \OpenAPI\Client\Model\CdnSettingsStale|null
     */
    public function getStale()
    {
        return $this->container['stale'];
    }

    /**
     * Sets stale
     *
     * @param \OpenAPI\Client\Model\CdnSettingsStale|null $stale stale
     *
     * @return self
     */
    public function setStale($stale)
    {

        if (is_null($stale)) {
            throw new \InvalidArgumentException('non-nullable stale cannot be null');
        }

        $this->container['stale'] = $stale;

        return $this;
    }

    /**
     * Gets geo_acl
     *
     * @return \OpenAPI\Client\Model\CdnSettingsGeoAcl|null
     */
    public function getGeoAcl()
    {
        return $this->container['geo_acl'];
    }

    /**
     * Sets geo_acl
     *
     * @param \OpenAPI\Client\Model\CdnSettingsGeoAcl|null $geo_acl geo_acl
     *
     * @return self
     */
    public function setGeoAcl($geo_acl)
    {

        if (is_null($geo_acl)) {
            throw new \InvalidArgumentException('non-nullable geo_acl cannot be null');
        }

        $this->container['geo_acl'] = $geo_acl;

        return $this;
    }

    /**
     * Gets referer_acl
     *
     * @return \OpenAPI\Client\Model\CdnSettingsRefererAcl|null
     */
    public function getRefererAcl()
    {
        return $this->container['referer_acl'];
    }

    /**
     * Sets referer_acl
     *
     * @param \OpenAPI\Client\Model\CdnSettingsRefererAcl|null $referer_acl referer_acl
     *
     * @return self
     */
    public function setRefererAcl($referer_acl)
    {

        if (is_null($referer_acl)) {
            throw new \InvalidArgumentException('non-nullable referer_acl cannot be null');
        }

        $this->container['referer_acl'] = $referer_acl;

        return $this;
    }

    /**
     * Gets ip_address_acl
     *
     * @return \OpenAPI\Client\Model\CdnSettingsIpAddressAcl|null
     */
    public function getIpAddressAcl()
    {
        return $this->container['ip_address_acl'];
    }

    /**
     * Sets ip_address_acl
     *
     * @param \OpenAPI\Client\Model\CdnSettingsIpAddressAcl|null $ip_address_acl ip_address_acl
     *
     * @return self
     */
    public function setIpAddressAcl($ip_address_acl)
    {

        if (is_null($ip_address_acl)) {
            throw new \InvalidArgumentException('non-nullable ip_address_acl cannot be null');
        }

        $this->container['ip_address_acl'] = $ip_address_acl;

        return $this;
    }

    /**
     * Gets redirect_http_to_https
     *
     * @return bool|null
     */
    public function getRedirectHttpToHttps()
    {
        return $this->container['redirect_http_to_https'];
    }

    /**
     * Sets redirect_http_to_https
     *
     * @param bool|null $redirect_http_to_https redirect_http_to_https
     *
     * @return self
     */
    public function setRedirectHttpToHttps($redirect_http_to_https)
    {

        if (is_null($redirect_http_to_https)) {
            throw new \InvalidArgumentException('non-nullable redirect_http_to_https cannot be null');
        }

        $this->container['redirect_http_to_https'] = $redirect_http_to_https;

        return $this;
    }

    /**
     * Gets user_agent_acl
     *
     * @return \OpenAPI\Client\Model\CdnSettingsUserAgentAcl|null
     */
    public function getUserAgentAcl()
    {
        return $this->container['user_agent_acl'];
    }

    /**
     * Sets user_agent_acl
     *
     * @param \OpenAPI\Client\Model\CdnSettingsUserAgentAcl|null $user_agent_acl user_agent_acl
     *
     * @return self
     */
    public function setUserAgentAcl($user_agent_acl)
    {

        if (is_null($user_agent_acl)) {
            throw new \InvalidArgumentException('non-nullable user_agent_acl cannot be null');
        }

        $this->container['user_agent_acl'] = $user_agent_acl;

        return $this;
    }

    /**
     * Gets tokenized_url_secure_key
     *
     * @return \OpenAPI\Client\Model\CdnSettingsTokenizedUrlSecureKey|null
     */
    public function getTokenizedUrlSecureKey()
    {
        return $this->container['tokenized_url_secure_key'];
    }

    /**
     * Sets tokenized_url_secure_key
     *
     * @param \OpenAPI\Client\Model\CdnSettingsTokenizedUrlSecureKey|null $tokenized_url_secure_key tokenized_url_secure_key
     *
     * @return self
     */
    public function setTokenizedUrlSecureKey($tokenized_url_secure_key)
    {

        if (is_null($tokenized_url_secure_key)) {
            throw new \InvalidArgumentException('non-nullable tokenized_url_secure_key cannot be null');
        }

        $this->container['tokenized_url_secure_key'] = $tokenized_url_secure_key;

        return $this;
    }

    /**
     * Gets allowed_http_methods
     *
     * @return \OpenAPI\Client\Model\CdnSettingsAllowedHttpMethods|null
     */
    public function getAllowedHttpMethods()
    {
        return $this->container['allowed_http_methods'];
    }

    /**
     * Sets allowed_http_methods
     *
     * @param \OpenAPI\Client\Model\CdnSettingsAllowedHttpMethods|null $allowed_http_methods allowed_http_methods
     *
     * @return self
     */
    public function setAllowedHttpMethods($allowed_http_methods)
    {

        if (is_null($allowed_http_methods)) {
            throw new \InvalidArgumentException('non-nullable allowed_http_methods cannot be null');
        }

        $this->container['allowed_http_methods'] = $allowed_http_methods;

        return $this;
    }

    /**
     * Gets http3_enabled
     *
     * @return bool|null
     */
    public function getHttp3Enabled()
    {
        return $this->container['http3_enabled'];
    }

    /**
     * Sets http3_enabled
     *
     * @param bool|null $http3_enabled http3_enabled
     *
     * @return self
     */
    public function setHttp3Enabled($http3_enabled)
    {

        if (is_null($http3_enabled)) {
            throw new \InvalidArgumentException('non-nullable http3_enabled cannot be null');
        }

        $this->container['http3_enabled'] = $http3_enabled;

        return $this;
    }

    /**
     * Gets gzip_compression
     *
     * @return \OpenAPI\Client\Model\CdnSettingsGzipCompression|null
     */
    public function getGzipCompression()
    {
        return $this->container['gzip_compression'];
    }

    /**
     * Sets gzip_compression
     *
     * @param \OpenAPI\Client\Model\CdnSettingsGzipCompression|null $gzip_compression gzip_compression
     *
     * @return self
     */
    public function setGzipCompression($gzip_compression)
    {

        if (is_null($gzip_compression)) {
            throw new \InvalidArgumentException('non-nullable gzip_compression cannot be null');
        }

        $this->container['gzip_compression'] = $gzip_compression;

        return $this;
    }

    /**
     * Gets content_slice
     *
     * @return bool|null
     */
    public function getContentSlice()
    {
        return $this->container['content_slice'];
    }

    /**
     * Sets content_slice
     *
     * @param bool|null $content_slice content_slice
     *
     * @return self
     */
    public function setContentSlice($content_slice)
    {

        if (is_null($content_slice)) {
            throw new \InvalidArgumentException('non-nullable content_slice cannot be null');
        }

        $this->container['content_slice'] = $content_slice;

        return $this;
    }

    /**
     * Gets static_request_headers
     *
     * @return \OpenAPI\Client\Model\CdnSettingsStaticRequestHeaders|null
     */
    public function getStaticRequestHeaders()
    {
        return $this->container['static_request_headers'];
    }

    /**
     * Sets static_request_headers
     *
     * @param \OpenAPI\Client\Model\CdnSettingsStaticRequestHeaders|null $static_request_headers static_request_headers
     *
     * @return self
     */
    public function setStaticRequestHeaders($static_request_headers)
    {

        if (is_null($static_request_headers)) {
            throw new \InvalidArgumentException('non-nullable static_request_headers cannot be null');
        }

        $this->container['static_request_headers'] = $static_request_headers;

        return $this;
    }

    /**
     * Gets cors
     *
     * @return \OpenAPI\Client\Model\CdnSettingsCors|null
     */
    public function getCors()
    {
        return $this->container['cors'];
    }

    /**
     * Sets cors
     *
     * @param \OpenAPI\Client\Model\CdnSettingsCors|null $cors cors
     *
     * @return self
     */
    public function setCors($cors)
    {

        if (is_null($cors)) {
            throw new \InvalidArgumentException('non-nullable cors cannot be null');
        }

        $this->container['cors'] = $cors;

        return $this;
    }

    /**
     * Gets static_response_headers
     *
     * @return \OpenAPI\Client\Model\CdnSettingsStaticResponseHeader|null
     */
    public function getStaticResponseHeaders()
    {
        return $this->container['static_response_headers'];
    }

    /**
     * Sets static_response_headers
     *
     * @param \OpenAPI\Client\Model\CdnSettingsStaticResponseHeader|null $static_response_headers static_response_headers
     *
     * @return self
     */
    public function setStaticResponseHeaders($static_response_headers)
    {

        if (is_null($static_response_headers)) {
            throw new \InvalidArgumentException('non-nullable static_response_headers cannot be null');
        }

        $this->container['static_response_headers'] = $static_response_headers;

        return $this;
    }

    /**
     * Gets response_headers_hiding_policy
     *
     * @return \OpenAPI\Client\Model\CdnSettingsResponseHeadersHidingPolicy|null
     */
    public function getResponseHeadersHidingPolicy()
    {
        return $this->container['response_headers_hiding_policy'];
    }

    /**
     * Sets response_headers_hiding_policy
     *
     * @param \OpenAPI\Client\Model\CdnSettingsResponseHeadersHidingPolicy|null $response_headers_hiding_policy response_headers_hiding_policy
     *
     * @return self
     */
    public function setResponseHeadersHidingPolicy($response_headers_hiding_policy)
    {

        if (is_null($response_headers_hiding_policy)) {
            throw new \InvalidArgumentException('non-nullable response_headers_hiding_policy cannot be null');
        }

        $this->container['response_headers_hiding_policy'] = $response_headers_hiding_policy;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


