<?php
/**
 * CloudService
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Управляемых сервисов
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.6.2
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * CloudService Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CloudService implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Cloud_Service';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'configuration_id' => 'string',
        'display_name' => 'string',
        'description' => 'string',
        'project_id' => 'string',
        'ui_pinned' => 'bool',
        'ui_pin_changed_at' => 'string',
        'status' => 'string',
        'status_details' => 'string',
        'created_at' => 'string',
        'price_day' => 'float',
        'price_month' => 'float',
        'mysql5' => '\OpenAPI\Client\Model\MysqlMysql5',
        'mysql8' => '\OpenAPI\Client\Model\MysqlMysql8',
        'mysql84' => '\OpenAPI\Client\Model\MysqlMysql84',
        'postgresql15' => '\OpenAPI\Client\Model\PostgresqlPostgresql15',
        'postgresql14' => '\OpenAPI\Client\Model\PostgresqlPostgresql14',
        'postgresql164' => '\OpenAPI\Client\Model\PostgresqlPostgresql164',
        's3' => '\OpenAPI\Client\Model\S3S3',
        'cdn' => '\OpenAPI\Client\Model\CdnCdn',
        'manage_enabled' => 'bool',
        'slug' => 'string',
        'monitorable_resources' => 'string[]',
        'unblocking' => 'bool',
        'migrating' => 'bool',
        'region' => 'string',
        'type' => 'string',
        'restoring' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => null,
        'configuration_id' => null,
        'display_name' => null,
        'description' => null,
        'project_id' => null,
        'ui_pinned' => null,
        'ui_pin_changed_at' => null,
        'status' => 'enum',
        'status_details' => 'enum',
        'created_at' => null,
        'price_day' => 'double',
        'price_month' => 'double',
        'mysql5' => null,
        'mysql8' => null,
        'mysql84' => null,
        'postgresql15' => null,
        'postgresql14' => null,
        'postgresql164' => null,
        's3' => null,
        'cdn' => null,
        'manage_enabled' => null,
        'slug' => null,
        'monitorable_resources' => null,
        'unblocking' => null,
        'migrating' => null,
        'region' => null,
        'type' => 'enum',
        'restoring' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
		'configuration_id' => false,
		'display_name' => false,
		'description' => false,
		'project_id' => false,
		'ui_pinned' => false,
		'ui_pin_changed_at' => false,
		'status' => false,
		'status_details' => false,
		'created_at' => false,
		'price_day' => false,
		'price_month' => false,
		'mysql5' => false,
		'mysql8' => false,
		'mysql84' => false,
		'postgresql15' => false,
		'postgresql14' => false,
		'postgresql164' => false,
		's3' => false,
		'cdn' => false,
		'manage_enabled' => false,
		'slug' => false,
		'monitorable_resources' => false,
		'unblocking' => false,
		'migrating' => false,
		'region' => false,
		'type' => false,
		'restoring' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'configuration_id' => 'configuration_id',
        'display_name' => 'display_name',
        'description' => 'description',
        'project_id' => 'project_id',
        'ui_pinned' => 'ui_pinned',
        'ui_pin_changed_at' => 'ui_pin_changed_at',
        'status' => 'status',
        'status_details' => 'status_details',
        'created_at' => 'created_at',
        'price_day' => 'price_day',
        'price_month' => 'price_month',
        'mysql5' => 'mysql5',
        'mysql8' => 'mysql8',
        'mysql84' => 'mysql84',
        'postgresql15' => 'postgresql15',
        'postgresql14' => 'postgresql14',
        'postgresql164' => 'postgresql164',
        's3' => 's3',
        'cdn' => 'cdn',
        'manage_enabled' => 'manage_enabled',
        'slug' => 'slug',
        'monitorable_resources' => 'monitorable_resources',
        'unblocking' => 'unblocking',
        'migrating' => 'migrating',
        'region' => 'region',
        'type' => 'type',
        'restoring' => 'restoring'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'configuration_id' => 'setConfigurationId',
        'display_name' => 'setDisplayName',
        'description' => 'setDescription',
        'project_id' => 'setProjectId',
        'ui_pinned' => 'setUiPinned',
        'ui_pin_changed_at' => 'setUiPinChangedAt',
        'status' => 'setStatus',
        'status_details' => 'setStatusDetails',
        'created_at' => 'setCreatedAt',
        'price_day' => 'setPriceDay',
        'price_month' => 'setPriceMonth',
        'mysql5' => 'setMysql5',
        'mysql8' => 'setMysql8',
        'mysql84' => 'setMysql84',
        'postgresql15' => 'setPostgresql15',
        'postgresql14' => 'setPostgresql14',
        'postgresql164' => 'setPostgresql164',
        's3' => 'setS3',
        'cdn' => 'setCdn',
        'manage_enabled' => 'setManageEnabled',
        'slug' => 'setSlug',
        'monitorable_resources' => 'setMonitorableResources',
        'unblocking' => 'setUnblocking',
        'migrating' => 'setMigrating',
        'region' => 'setRegion',
        'type' => 'setType',
        'restoring' => 'setRestoring'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'configuration_id' => 'getConfigurationId',
        'display_name' => 'getDisplayName',
        'description' => 'getDescription',
        'project_id' => 'getProjectId',
        'ui_pinned' => 'getUiPinned',
        'ui_pin_changed_at' => 'getUiPinChangedAt',
        'status' => 'getStatus',
        'status_details' => 'getStatusDetails',
        'created_at' => 'getCreatedAt',
        'price_day' => 'getPriceDay',
        'price_month' => 'getPriceMonth',
        'mysql5' => 'getMysql5',
        'mysql8' => 'getMysql8',
        'mysql84' => 'getMysql84',
        'postgresql15' => 'getPostgresql15',
        'postgresql14' => 'getPostgresql14',
        'postgresql164' => 'getPostgresql164',
        's3' => 'getS3',
        'cdn' => 'getCdn',
        'manage_enabled' => 'getManageEnabled',
        'slug' => 'getSlug',
        'monitorable_resources' => 'getMonitorableResources',
        'unblocking' => 'getUnblocking',
        'migrating' => 'getMigrating',
        'region' => 'getRegion',
        'type' => 'getType',
        'restoring' => 'getRestoring'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const STATUS_CREATING = 'CREATING';
    public const STATUS_RUNNING = 'RUNNING';
    public const STATUS_RESTARTING = 'RESTARTING';
    public const STATUS_STOPPED = 'STOPPED';
    public const STATUS_RECONFIGURING = 'RECONFIGURING';
    public const STATUS_SUSPENDED = 'SUSPENDED';
    public const STATUS_DETAILS_UNDERSCORE = '_';
    public const STATUS_DETAILS_SUSPENDED_INSUFFICIENT_FUNDS = 'SUSPENDED_INSUFFICIENT_FUNDS';
    public const STATUS_DETAILS_SUSPENDED_SERVICE_MAINTENANCE = 'SUSPENDED_SERVICE_MAINTENANCE';
    public const TYPE_MYSQL5 = 'MYSQL5';
    public const TYPE_MYSQL8 = 'MYSQL8';
    public const TYPE_MYSQL84 = 'MYSQL84';
    public const TYPE_POSTGRESQL14 = 'POSTGRESQL14';
    public const TYPE_POSTGRESQL15 = 'POSTGRESQL15';
    public const TYPE_POSTGRESQL164 = 'POSTGRESQL164';
    public const TYPE_S_3 = 'S_3';
    public const TYPE_CDN = 'CDN';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getStatusAllowableValues()
    {
        return [
            self::STATUS_CREATING,
            self::STATUS_RUNNING,
            self::STATUS_RESTARTING,
            self::STATUS_STOPPED,
            self::STATUS_RECONFIGURING,
            self::STATUS_SUSPENDED,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getStatusDetailsAllowableValues()
    {
        return [
            self::STATUS_DETAILS_UNDERSCORE,
            self::STATUS_DETAILS_SUSPENDED_INSUFFICIENT_FUNDS,
            self::STATUS_DETAILS_SUSPENDED_SERVICE_MAINTENANCE,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getTypeAllowableValues()
    {
        return [
            self::TYPE_MYSQL5,
            self::TYPE_MYSQL8,
            self::TYPE_MYSQL84,
            self::TYPE_POSTGRESQL14,
            self::TYPE_POSTGRESQL15,
            self::TYPE_POSTGRESQL164,
            self::TYPE_S_3,
            self::TYPE_CDN,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('configuration_id', $data ?? [], null);
        $this->setIfExists('display_name', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('project_id', $data ?? [], null);
        $this->setIfExists('ui_pinned', $data ?? [], null);
        $this->setIfExists('ui_pin_changed_at', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('status_details', $data ?? [], null);
        $this->setIfExists('created_at', $data ?? [], null);
        $this->setIfExists('price_day', $data ?? [], null);
        $this->setIfExists('price_month', $data ?? [], null);
        $this->setIfExists('mysql5', $data ?? [], null);
        $this->setIfExists('mysql8', $data ?? [], null);
        $this->setIfExists('mysql84', $data ?? [], null);
        $this->setIfExists('postgresql15', $data ?? [], null);
        $this->setIfExists('postgresql14', $data ?? [], null);
        $this->setIfExists('postgresql164', $data ?? [], null);
        $this->setIfExists('s3', $data ?? [], null);
        $this->setIfExists('cdn', $data ?? [], null);
        $this->setIfExists('manage_enabled', $data ?? [], null);
        $this->setIfExists('slug', $data ?? [], null);
        $this->setIfExists('monitorable_resources', $data ?? [], null);
        $this->setIfExists('unblocking', $data ?? [], null);
        $this->setIfExists('migrating', $data ?? [], null);
        $this->setIfExists('region', $data ?? [], null);
        $this->setIfExists('type', $data ?? [], null);
        $this->setIfExists('restoring', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getStatusAllowableValues();
        if (!is_null($this->container['status']) && !in_array($this->container['status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'status', must be one of '%s'",
                $this->container['status'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getStatusDetailsAllowableValues();
        if (!is_null($this->container['status_details']) && !in_array($this->container['status_details'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'status_details', must be one of '%s'",
                $this->container['status_details'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getTypeAllowableValues();
        if (!is_null($this->container['type']) && !in_array($this->container['type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'type', must be one of '%s'",
                $this->container['type'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id id
     *
     * @return self
     */
    public function setId($id)
    {

        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }

        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets configuration_id
     *
     * @return string|null
     */
    public function getConfigurationId()
    {
        return $this->container['configuration_id'];
    }

    /**
     * Sets configuration_id
     *
     * @param string|null $configuration_id configuration_id
     *
     * @return self
     */
    public function setConfigurationId($configuration_id)
    {

        if (is_null($configuration_id)) {
            throw new \InvalidArgumentException('non-nullable configuration_id cannot be null');
        }

        $this->container['configuration_id'] = $configuration_id;

        return $this;
    }

    /**
     * Gets display_name
     *
     * @return string|null
     */
    public function getDisplayName()
    {
        return $this->container['display_name'];
    }

    /**
     * Sets display_name
     *
     * @param string|null $display_name display_name
     *
     * @return self
     */
    public function setDisplayName($display_name)
    {

        if (is_null($display_name)) {
            throw new \InvalidArgumentException('non-nullable display_name cannot be null');
        }

        $this->container['display_name'] = $display_name;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description description
     *
     * @return self
     */
    public function setDescription($description)
    {

        if (is_null($description)) {
            throw new \InvalidArgumentException('non-nullable description cannot be null');
        }

        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets project_id
     *
     * @return string|null
     */
    public function getProjectId()
    {
        return $this->container['project_id'];
    }

    /**
     * Sets project_id
     *
     * @param string|null $project_id project_id
     *
     * @return self
     */
    public function setProjectId($project_id)
    {

        if (is_null($project_id)) {
            throw new \InvalidArgumentException('non-nullable project_id cannot be null');
        }

        $this->container['project_id'] = $project_id;

        return $this;
    }

    /**
     * Gets ui_pinned
     *
     * @return bool|null
     */
    public function getUiPinned()
    {
        return $this->container['ui_pinned'];
    }

    /**
     * Sets ui_pinned
     *
     * @param bool|null $ui_pinned ui_pinned
     *
     * @return self
     */
    public function setUiPinned($ui_pinned)
    {

        if (is_null($ui_pinned)) {
            throw new \InvalidArgumentException('non-nullable ui_pinned cannot be null');
        }

        $this->container['ui_pinned'] = $ui_pinned;

        return $this;
    }

    /**
     * Gets ui_pin_changed_at
     *
     * @return string|null
     */
    public function getUiPinChangedAt()
    {
        return $this->container['ui_pin_changed_at'];
    }

    /**
     * Sets ui_pin_changed_at
     *
     * @param string|null $ui_pin_changed_at ui_pin_changed_at
     *
     * @return self
     */
    public function setUiPinChangedAt($ui_pin_changed_at)
    {

        if (is_null($ui_pin_changed_at)) {
            throw new \InvalidArgumentException('non-nullable ui_pin_changed_at cannot be null');
        }

        $this->container['ui_pin_changed_at'] = $ui_pin_changed_at;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string|null
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string|null $status status
     *
     * @return self
     */
    public function setStatus($status)
    {
        $allowedValues = $this->getStatusAllowableValues();
        if (!is_null($status) && !in_array($status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'status', must be one of '%s'",
                    $status,
                    implode("', '", $allowedValues)
                )
            );
        }

        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }

        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets status_details
     *
     * @return string|null
     */
    public function getStatusDetails()
    {
        return $this->container['status_details'];
    }

    /**
     * Sets status_details
     *
     * @param string|null $status_details status_details
     *
     * @return self
     */
    public function setStatusDetails($status_details)
    {
        $allowedValues = $this->getStatusDetailsAllowableValues();
        if (!is_null($status_details) && !in_array($status_details, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'status_details', must be one of '%s'",
                    $status_details,
                    implode("', '", $allowedValues)
                )
            );
        }

        if (is_null($status_details)) {
            throw new \InvalidArgumentException('non-nullable status_details cannot be null');
        }

        $this->container['status_details'] = $status_details;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return string|null
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param string|null $created_at created_at
     *
     * @return self
     */
    public function setCreatedAt($created_at)
    {

        if (is_null($created_at)) {
            throw new \InvalidArgumentException('non-nullable created_at cannot be null');
        }

        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets price_day
     *
     * @return float|null
     */
    public function getPriceDay()
    {
        return $this->container['price_day'];
    }

    /**
     * Sets price_day
     *
     * @param float|null $price_day price_day
     *
     * @return self
     */
    public function setPriceDay($price_day)
    {

        if (is_null($price_day)) {
            throw new \InvalidArgumentException('non-nullable price_day cannot be null');
        }

        $this->container['price_day'] = $price_day;

        return $this;
    }

    /**
     * Gets price_month
     *
     * @return float|null
     */
    public function getPriceMonth()
    {
        return $this->container['price_month'];
    }

    /**
     * Sets price_month
     *
     * @param float|null $price_month price_month
     *
     * @return self
     */
    public function setPriceMonth($price_month)
    {

        if (is_null($price_month)) {
            throw new \InvalidArgumentException('non-nullable price_month cannot be null');
        }

        $this->container['price_month'] = $price_month;

        return $this;
    }

    /**
     * Gets mysql5
     *
     * @return \OpenAPI\Client\Model\MysqlMysql5|null
     */
    public function getMysql5()
    {
        return $this->container['mysql5'];
    }

    /**
     * Sets mysql5
     *
     * @param \OpenAPI\Client\Model\MysqlMysql5|null $mysql5 mysql5
     *
     * @return self
     */
    public function setMysql5($mysql5)
    {

        if (is_null($mysql5)) {
            throw new \InvalidArgumentException('non-nullable mysql5 cannot be null');
        }

        $this->container['mysql5'] = $mysql5;

        return $this;
    }

    /**
     * Gets mysql8
     *
     * @return \OpenAPI\Client\Model\MysqlMysql8|null
     */
    public function getMysql8()
    {
        return $this->container['mysql8'];
    }

    /**
     * Sets mysql8
     *
     * @param \OpenAPI\Client\Model\MysqlMysql8|null $mysql8 mysql8
     *
     * @return self
     */
    public function setMysql8($mysql8)
    {

        if (is_null($mysql8)) {
            throw new \InvalidArgumentException('non-nullable mysql8 cannot be null');
        }

        $this->container['mysql8'] = $mysql8;

        return $this;
    }

    /**
     * Gets mysql84
     *
     * @return \OpenAPI\Client\Model\MysqlMysql84|null
     */
    public function getMysql84()
    {
        return $this->container['mysql84'];
    }

    /**
     * Sets mysql84
     *
     * @param \OpenAPI\Client\Model\MysqlMysql84|null $mysql84 mysql84
     *
     * @return self
     */
    public function setMysql84($mysql84)
    {

        if (is_null($mysql84)) {
            throw new \InvalidArgumentException('non-nullable mysql84 cannot be null');
        }

        $this->container['mysql84'] = $mysql84;

        return $this;
    }

    /**
     * Gets postgresql15
     *
     * @return \OpenAPI\Client\Model\PostgresqlPostgresql15|null
     */
    public function getPostgresql15()
    {
        return $this->container['postgresql15'];
    }

    /**
     * Sets postgresql15
     *
     * @param \OpenAPI\Client\Model\PostgresqlPostgresql15|null $postgresql15 postgresql15
     *
     * @return self
     */
    public function setPostgresql15($postgresql15)
    {

        if (is_null($postgresql15)) {
            throw new \InvalidArgumentException('non-nullable postgresql15 cannot be null');
        }

        $this->container['postgresql15'] = $postgresql15;

        return $this;
    }

    /**
     * Gets postgresql14
     *
     * @return \OpenAPI\Client\Model\PostgresqlPostgresql14|null
     */
    public function getPostgresql14()
    {
        return $this->container['postgresql14'];
    }

    /**
     * Sets postgresql14
     *
     * @param \OpenAPI\Client\Model\PostgresqlPostgresql14|null $postgresql14 postgresql14
     *
     * @return self
     */
    public function setPostgresql14($postgresql14)
    {

        if (is_null($postgresql14)) {
            throw new \InvalidArgumentException('non-nullable postgresql14 cannot be null');
        }

        $this->container['postgresql14'] = $postgresql14;

        return $this;
    }

    /**
     * Gets postgresql164
     *
     * @return \OpenAPI\Client\Model\PostgresqlPostgresql164|null
     */
    public function getPostgresql164()
    {
        return $this->container['postgresql164'];
    }

    /**
     * Sets postgresql164
     *
     * @param \OpenAPI\Client\Model\PostgresqlPostgresql164|null $postgresql164 postgresql164
     *
     * @return self
     */
    public function setPostgresql164($postgresql164)
    {

        if (is_null($postgresql164)) {
            throw new \InvalidArgumentException('non-nullable postgresql164 cannot be null');
        }

        $this->container['postgresql164'] = $postgresql164;

        return $this;
    }

    /**
     * Gets s3
     *
     * @return \OpenAPI\Client\Model\S3S3|null
     */
    public function getS3()
    {
        return $this->container['s3'];
    }

    /**
     * Sets s3
     *
     * @param \OpenAPI\Client\Model\S3S3|null $s3 s3
     *
     * @return self
     */
    public function setS3($s3)
    {

        if (is_null($s3)) {
            throw new \InvalidArgumentException('non-nullable s3 cannot be null');
        }

        $this->container['s3'] = $s3;

        return $this;
    }

    /**
     * Gets cdn
     *
     * @return \OpenAPI\Client\Model\CdnCdn|null
     */
    public function getCdn()
    {
        return $this->container['cdn'];
    }

    /**
     * Sets cdn
     *
     * @param \OpenAPI\Client\Model\CdnCdn|null $cdn cdn
     *
     * @return self
     */
    public function setCdn($cdn)
    {

        if (is_null($cdn)) {
            throw new \InvalidArgumentException('non-nullable cdn cannot be null');
        }

        $this->container['cdn'] = $cdn;

        return $this;
    }

    /**
     * Gets manage_enabled
     *
     * @return bool|null
     */
    public function getManageEnabled()
    {
        return $this->container['manage_enabled'];
    }

    /**
     * Sets manage_enabled
     *
     * @param bool|null $manage_enabled manage_enabled
     *
     * @return self
     */
    public function setManageEnabled($manage_enabled)
    {

        if (is_null($manage_enabled)) {
            throw new \InvalidArgumentException('non-nullable manage_enabled cannot be null');
        }

        $this->container['manage_enabled'] = $manage_enabled;

        return $this;
    }

    /**
     * Gets slug
     *
     * @return string|null
     */
    public function getSlug()
    {
        return $this->container['slug'];
    }

    /**
     * Sets slug
     *
     * @param string|null $slug slug
     *
     * @return self
     */
    public function setSlug($slug)
    {

        if (is_null($slug)) {
            throw new \InvalidArgumentException('non-nullable slug cannot be null');
        }

        $this->container['slug'] = $slug;

        return $this;
    }

    /**
     * Gets monitorable_resources
     *
     * @return string[]|null
     */
    public function getMonitorableResources()
    {
        return $this->container['monitorable_resources'];
    }

    /**
     * Sets monitorable_resources
     *
     * @param string[]|null $monitorable_resources monitorable_resources
     *
     * @return self
     */
    public function setMonitorableResources($monitorable_resources)
    {

        if (is_null($monitorable_resources)) {
            throw new \InvalidArgumentException('non-nullable monitorable_resources cannot be null');
        }

        $this->container['monitorable_resources'] = $monitorable_resources;

        return $this;
    }

    /**
     * Gets unblocking
     *
     * @return bool|null
     */
    public function getUnblocking()
    {
        return $this->container['unblocking'];
    }

    /**
     * Sets unblocking
     *
     * @param bool|null $unblocking unblocking
     *
     * @return self
     */
    public function setUnblocking($unblocking)
    {

        if (is_null($unblocking)) {
            throw new \InvalidArgumentException('non-nullable unblocking cannot be null');
        }

        $this->container['unblocking'] = $unblocking;

        return $this;
    }

    /**
     * Gets migrating
     *
     * @return bool|null
     */
    public function getMigrating()
    {
        return $this->container['migrating'];
    }

    /**
     * Sets migrating
     *
     * @param bool|null $migrating migrating
     *
     * @return self
     */
    public function setMigrating($migrating)
    {

        if (is_null($migrating)) {
            throw new \InvalidArgumentException('non-nullable migrating cannot be null');
        }

        $this->container['migrating'] = $migrating;

        return $this;
    }

    /**
     * Gets region
     *
     * @return string|null
     */
    public function getRegion()
    {
        return $this->container['region'];
    }

    /**
     * Sets region
     *
     * @param string|null $region region
     *
     * @return self
     */
    public function setRegion($region)
    {

        if (is_null($region)) {
            throw new \InvalidArgumentException('non-nullable region cannot be null');
        }

        $this->container['region'] = $region;

        return $this;
    }

    /**
     * Gets type
     *
     * @return string|null
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string|null $type type
     *
     * @return self
     */
    public function setType($type)
    {
        $allowedValues = $this->getTypeAllowableValues();
        if (!is_null($type) && !in_array($type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'type', must be one of '%s'",
                    $type,
                    implode("', '", $allowedValues)
                )
            );
        }

        if (is_null($type)) {
            throw new \InvalidArgumentException('non-nullable type cannot be null');
        }

        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets restoring
     *
     * @return bool|null
     */
    public function getRestoring()
    {
        return $this->container['restoring'];
    }

    /**
     * Sets restoring
     *
     * @param bool|null $restoring restoring
     *
     * @return self
     */
    public function setRestoring($restoring)
    {

        if (is_null($restoring)) {
            throw new \InvalidArgumentException('non-nullable restoring cannot be null');
        }

        $this->container['restoring'] = $restoring;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


