<?php
/**
 * MysqlMysql8Configuration
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Управляемых сервисов
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.4.1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * MysqlMysql8Configuration Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class MysqlMysql8Configuration implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Mysql_Mysql8Configuration';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'cpu_count' => 'int',
        'disk_size' => 'int',
        'memory' => 'int',
        'version' => 'string',
        'display_version' => 'string',
        'param_config' => '\OpenAPI\Client\Model\StructuresParamConfig[]',
        'param_default' => 'array<string,string>'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'cpu_count' => 'uint32',
        'disk_size' => 'uint32',
        'memory' => 'uint32',
        'version' => null,
        'display_version' => null,
        'param_config' => null,
        'param_default' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'cpu_count' => false,
		'disk_size' => false,
		'memory' => false,
		'version' => false,
		'display_version' => false,
		'param_config' => false,
		'param_default' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'cpu_count' => 'cpu_count',
        'disk_size' => 'disk_size',
        'memory' => 'memory',
        'version' => 'version',
        'display_version' => 'display_version',
        'param_config' => 'param_config',
        'param_default' => 'param_default'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'cpu_count' => 'setCpuCount',
        'disk_size' => 'setDiskSize',
        'memory' => 'setMemory',
        'version' => 'setVersion',
        'display_version' => 'setDisplayVersion',
        'param_config' => 'setParamConfig',
        'param_default' => 'setParamDefault'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'cpu_count' => 'getCpuCount',
        'disk_size' => 'getDiskSize',
        'memory' => 'getMemory',
        'version' => 'getVersion',
        'display_version' => 'getDisplayVersion',
        'param_config' => 'getParamConfig',
        'param_default' => 'getParamDefault'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('cpu_count', $data ?? [], null);
        $this->setIfExists('disk_size', $data ?? [], null);
        $this->setIfExists('memory', $data ?? [], null);
        $this->setIfExists('version', $data ?? [], null);
        $this->setIfExists('display_version', $data ?? [], null);
        $this->setIfExists('param_config', $data ?? [], null);
        $this->setIfExists('param_default', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets cpu_count
     *
     * @return int|null
     */
    public function getCpuCount()
    {
        return $this->container['cpu_count'];
    }

    /**
     * Sets cpu_count
     *
     * @param int|null $cpu_count cpu_count
     *
     * @return self
     */
    public function setCpuCount($cpu_count)
    {

        if (is_null($cpu_count)) {
            throw new \InvalidArgumentException('non-nullable cpu_count cannot be null');
        }

        $this->container['cpu_count'] = $cpu_count;

        return $this;
    }

    /**
     * Gets disk_size
     *
     * @return int|null
     */
    public function getDiskSize()
    {
        return $this->container['disk_size'];
    }

    /**
     * Sets disk_size
     *
     * @param int|null $disk_size disk_size
     *
     * @return self
     */
    public function setDiskSize($disk_size)
    {

        if (is_null($disk_size)) {
            throw new \InvalidArgumentException('non-nullable disk_size cannot be null');
        }

        $this->container['disk_size'] = $disk_size;

        return $this;
    }

    /**
     * Gets memory
     *
     * @return int|null
     */
    public function getMemory()
    {
        return $this->container['memory'];
    }

    /**
     * Sets memory
     *
     * @param int|null $memory memory
     *
     * @return self
     */
    public function setMemory($memory)
    {

        if (is_null($memory)) {
            throw new \InvalidArgumentException('non-nullable memory cannot be null');
        }

        $this->container['memory'] = $memory;

        return $this;
    }

    /**
     * Gets version
     *
     * @return string|null
     */
    public function getVersion()
    {
        return $this->container['version'];
    }

    /**
     * Sets version
     *
     * @param string|null $version version
     *
     * @return self
     */
    public function setVersion($version)
    {

        if (is_null($version)) {
            throw new \InvalidArgumentException('non-nullable version cannot be null');
        }

        $this->container['version'] = $version;

        return $this;
    }

    /**
     * Gets display_version
     *
     * @return string|null
     */
    public function getDisplayVersion()
    {
        return $this->container['display_version'];
    }

    /**
     * Sets display_version
     *
     * @param string|null $display_version display_version
     *
     * @return self
     */
    public function setDisplayVersion($display_version)
    {

        if (is_null($display_version)) {
            throw new \InvalidArgumentException('non-nullable display_version cannot be null');
        }

        $this->container['display_version'] = $display_version;

        return $this;
    }

    /**
     * Gets param_config
     *
     * @return \OpenAPI\Client\Model\StructuresParamConfig[]|null
     */
    public function getParamConfig()
    {
        return $this->container['param_config'];
    }

    /**
     * Sets param_config
     *
     * @param \OpenAPI\Client\Model\StructuresParamConfig[]|null $param_config param_config
     *
     * @return self
     */
    public function setParamConfig($param_config)
    {

        if (is_null($param_config)) {
            throw new \InvalidArgumentException('non-nullable param_config cannot be null');
        }

        $this->container['param_config'] = $param_config;

        return $this;
    }

    /**
     * Gets param_default
     *
     * @return array<string,string>|null
     */
    public function getParamDefault()
    {
        return $this->container['param_default'];
    }

    /**
     * Sets param_default
     *
     * @param array<string,string>|null $param_default param_default
     *
     * @return self
     */
    public function setParamDefault($param_default)
    {

        if (is_null($param_default)) {
            throw new \InvalidArgumentException('non-nullable param_default cannot be null');
        }

        $this->container['param_default'] = $param_default;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


