<?php
/**
 * NetworkDriveGetLimitsResponseLimits
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Управляемых сервисов
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.6.9
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * NetworkDriveGetLimitsResponseLimits Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class NetworkDriveGetLimitsResponseLimits implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'NetworkDrive_GetLimitsResponse_Limits';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'region' => 'string',
        'max_network_drives' => 'int',
        'available_network_drives' => 'int',
        'max_mounts_per_resource' => 'int',
        'max_total_size' => '\OpenAPI\Client\Model\NetworkDriveGetLimitsResponseLimitsTotalSize[]',
        'available_total_size' => '\OpenAPI\Client\Model\NetworkDriveGetLimitsResponseLimitsTotalSize[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'region' => null,
        'max_network_drives' => 'uint32',
        'available_network_drives' => 'uint32',
        'max_mounts_per_resource' => 'uint32',
        'max_total_size' => null,
        'available_total_size' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'region' => false,
		'max_network_drives' => false,
		'available_network_drives' => false,
		'max_mounts_per_resource' => false,
		'max_total_size' => false,
		'available_total_size' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'region' => 'region',
        'max_network_drives' => 'max_network_drives',
        'available_network_drives' => 'available_network_drives',
        'max_mounts_per_resource' => 'max_mounts_per_resource',
        'max_total_size' => 'max_total_size',
        'available_total_size' => 'available_total_size'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'region' => 'setRegion',
        'max_network_drives' => 'setMaxNetworkDrives',
        'available_network_drives' => 'setAvailableNetworkDrives',
        'max_mounts_per_resource' => 'setMaxMountsPerResource',
        'max_total_size' => 'setMaxTotalSize',
        'available_total_size' => 'setAvailableTotalSize'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'region' => 'getRegion',
        'max_network_drives' => 'getMaxNetworkDrives',
        'available_network_drives' => 'getAvailableNetworkDrives',
        'max_mounts_per_resource' => 'getMaxMountsPerResource',
        'max_total_size' => 'getMaxTotalSize',
        'available_total_size' => 'getAvailableTotalSize'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('region', $data ?? [], null);
        $this->setIfExists('max_network_drives', $data ?? [], null);
        $this->setIfExists('available_network_drives', $data ?? [], null);
        $this->setIfExists('max_mounts_per_resource', $data ?? [], null);
        $this->setIfExists('max_total_size', $data ?? [], null);
        $this->setIfExists('available_total_size', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets region
     *
     * @return string|null
     */
    public function getRegion()
    {
        return $this->container['region'];
    }

    /**
     * Sets region
     *
     * @param string|null $region region
     *
     * @return self
     */
    public function setRegion($region)
    {
        if (is_null($region)) {
            throw new \InvalidArgumentException('non-nullable region cannot be null');
        }
        $this->container['region'] = $region;

        return $this;
    }

    /**
     * Gets max_network_drives
     *
     * @return int|null
     */
    public function getMaxNetworkDrives()
    {
        return $this->container['max_network_drives'];
    }

    /**
     * Sets max_network_drives
     *
     * @param int|null $max_network_drives max_network_drives
     *
     * @return self
     */
    public function setMaxNetworkDrives($max_network_drives)
    {
        if (is_null($max_network_drives)) {
            throw new \InvalidArgumentException('non-nullable max_network_drives cannot be null');
        }
        $this->container['max_network_drives'] = $max_network_drives;

        return $this;
    }

    /**
     * Gets available_network_drives
     *
     * @return int|null
     */
    public function getAvailableNetworkDrives()
    {
        return $this->container['available_network_drives'];
    }

    /**
     * Sets available_network_drives
     *
     * @param int|null $available_network_drives available_network_drives
     *
     * @return self
     */
    public function setAvailableNetworkDrives($available_network_drives)
    {
        if (is_null($available_network_drives)) {
            throw new \InvalidArgumentException('non-nullable available_network_drives cannot be null');
        }
        $this->container['available_network_drives'] = $available_network_drives;

        return $this;
    }

    /**
     * Gets max_mounts_per_resource
     *
     * @return int|null
     */
    public function getMaxMountsPerResource()
    {
        return $this->container['max_mounts_per_resource'];
    }

    /**
     * Sets max_mounts_per_resource
     *
     * @param int|null $max_mounts_per_resource max_mounts_per_resource
     *
     * @return self
     */
    public function setMaxMountsPerResource($max_mounts_per_resource)
    {
        if (is_null($max_mounts_per_resource)) {
            throw new \InvalidArgumentException('non-nullable max_mounts_per_resource cannot be null');
        }
        $this->container['max_mounts_per_resource'] = $max_mounts_per_resource;

        return $this;
    }

    /**
     * Gets max_total_size
     *
     * @return \OpenAPI\Client\Model\NetworkDriveGetLimitsResponseLimitsTotalSize[]|null
     */
    public function getMaxTotalSize()
    {
        return $this->container['max_total_size'];
    }

    /**
     * Sets max_total_size
     *
     * @param \OpenAPI\Client\Model\NetworkDriveGetLimitsResponseLimitsTotalSize[]|null $max_total_size max_total_size
     *
     * @return self
     */
    public function setMaxTotalSize($max_total_size)
    {
        if (is_null($max_total_size)) {
            throw new \InvalidArgumentException('non-nullable max_total_size cannot be null');
        }
        $this->container['max_total_size'] = $max_total_size;

        return $this;
    }

    /**
     * Gets available_total_size
     *
     * @return \OpenAPI\Client\Model\NetworkDriveGetLimitsResponseLimitsTotalSize[]|null
     */
    public function getAvailableTotalSize()
    {
        return $this->container['available_total_size'];
    }

    /**
     * Sets available_total_size
     *
     * @param \OpenAPI\Client\Model\NetworkDriveGetLimitsResponseLimitsTotalSize[]|null $available_total_size available_total_size
     *
     * @return self
     */
    public function setAvailableTotalSize($available_total_size)
    {
        if (is_null($available_total_size)) {
            throw new \InvalidArgumentException('non-nullable available_total_size cannot be null');
        }
        $this->container['available_total_size'] = $available_total_size;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


