<?php
/**
 * PostgresqlServiceApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Управляемых сервисов
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.4.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * PostgresqlServiceApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PostgresqlServiceApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for postgresqlServiceCreateDb
     *
     * .
     *
     */
    public function testPostgresqlServiceCreateDb()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postgresqlServiceCreateRole
     *
     * .
     *
     */
    public function testPostgresqlServiceCreateRole()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postgresqlServiceGetConfig
     *
     * .
     *
     */
    public function testPostgresqlServiceGetConfig()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postgresqlServiceGetDbList
     *
     * .
     *
     */
    public function testPostgresqlServiceGetDbList()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postgresqlServiceGetRemoteAccess
     *
     * .
     *
     */
    public function testPostgresqlServiceGetRemoteAccess()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postgresqlServiceGetRoleList
     *
     * .
     *
     */
    public function testPostgresqlServiceGetRoleList()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postgresqlServiceRemoveDb
     *
     * .
     *
     */
    public function testPostgresqlServiceRemoveDb()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postgresqlServiceRemoveRole
     *
     * .
     *
     */
    public function testPostgresqlServiceRemoveRole()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postgresqlServiceSetConfig
     *
     * .
     *
     */
    public function testPostgresqlServiceSetConfig()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postgresqlServiceUpdateDb
     *
     * .
     *
     */
    public function testPostgresqlServiceUpdateDb()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postgresqlServiceUpdateRemoteAccess
     *
     * .
     *
     */
    public function testPostgresqlServiceUpdateRemoteAccess()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postgresqlServiceUpdateRole
     *
     * .
     *
     */
    public function testPostgresqlServiceUpdateRole()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
